'use client';

import { useState, useEffect } from 'react';
import { useAuth } from '@/contexts/AuthContext';
import { useRouter } from 'next/navigation';
import ProtectedRoute from '@/components/ProtectedRoute';
import { getPhishingStatistics, getAllPhishingAttempts } from '@/lib/phishingTracking';
import { getAllUsers } from '@/lib/userService';
import Link from 'next/link';
import { Shield, Users, AlertTriangle, Download, LogOut } from 'lucide-react';
import jsPDF from 'jspdf';

export default function AdminDashboard() {
  const { user, userData, signOut } = useAuth();
  const router = useRouter();

  const [stats, setStats] = useState(null);
  const [attempts, setAttempts] = useState([]);
  const [userMap, setUserMap] = useState({});
  const [loading, setLoading] = useState(true);
  const [selectedFilter, setSelectedFilter] = useState('all');

  useEffect(() => {
    loadData();
  }, []);

  const loadData = async () => {
    setLoading(true);
    try {
      const [statistics, allAttempts, users] = await Promise.all([
        getPhishingStatistics(),
        getAllPhishingAttempts(),
        getAllUsers().catch(() => [])
      ]);

      const map = {};
      users.forEach(u => {
        map[u.id] = u.name || u.email.split('@')[0] || 'Unknown User';
      });

      setStats(statistics);
      setAttempts(allAttempts);
      setUserMap(map);
    } catch (err) {
      console.error('Failed to load admin data:', err);
    } finally {
      setLoading(false);
    }
  };

  const filteredAttempts = selectedFilter === 'all'
    ? attempts
    : attempts.filter(a => a.phishingType === selectedFilter);

  const types = [
    { id: 'email', name: 'Email Phishing', icon: 'Email', color: 'bg-blue-100 text-blue-700' },
    { id: 'face', name: 'Facebook Login', icon: 'Facebook', color: 'bg-blue-100 text-blue-700' },
    { id: 'sms', name: 'SMS (Smishing)', icon: 'SMS', color: 'bg-green-100 text-green-700' },
    { id: 'social', name: 'Social Media', icon: 'Social', color: 'bg-pink-100 text-pink-700' },
    { id: 'qr', name: 'QR Code Attack', icon: 'QR', color: 'bg-orange-100 text-orange-700' },
  ];

  const exportPDF = () => {
    const doc = new jsPDF();

    // Header
    doc.setFontSize(22);
    doc.setTextColor(79, 70, 229); // Indigo-600
    doc.text("CyberAware Phishing Report", 14, 20);

    // Meta info
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Generated on: ${new Date().toLocaleString()}`, 14, 30);
    doc.text(`Generated by: ${userData?.name || user?.email || 'Admin'}`, 14, 35);

    // Statistics Section
    doc.setFontSize(16);
    doc.setTextColor(0);
    doc.text("Summary Statistics", 14, 50);

    doc.setFontSize(12);
    doc.text(`Total Attempts: ${stats?.totalAttempts || 0}`, 14, 60);
    doc.text(`Users Tested: ${stats?.uniqueUsers || 0}`, 14, 67);
    doc.text(`Avg Attempts/User: ${stats?.uniqueUsers ? (stats.totalAttempts / stats.uniqueUsers).toFixed(1) : '0'}`, 14, 74);

    // Table Section
    doc.setFontSize(16);
    doc.text("Recent Attempts Log", 14, 90);

    let y = 100;
    const pageHeight = doc.internal.pageSize.height;

    // Table Headers
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text("User", 14, y);
    doc.text("Type", 60, y);
    doc.text("Data Captured", 100, y);
    doc.text("Time", 150, y);

    doc.setDrawColor(200);
    doc.line(14, y + 2, 196, y + 2);

    y += 10;
    doc.setTextColor(0);

    filteredAttempts.forEach((a) => {
      if (y > pageHeight - 20) {
        doc.addPage();
        y = 20;
        // Re-print headers on new page
        doc.setFontSize(10);
        doc.setTextColor(100);
        doc.text("User", 14, y);
        doc.text("Type", 60, y);
        doc.text("Data Captured", 100, y);
        doc.text("Time", 150, y);
        doc.line(14, y + 2, 196, y + 2);
        y += 10;
        doc.setTextColor(0);
      }

      const userName = userMap[a.userId] || 'Unknown User';
      const typeName = types.find(t => t.id === a.phishingType)?.name || a.phishingType;
      const captured = Object.keys(a.capturedData || {}).join(', ') || 'None';
      const time = new Date(a.timestamp).toLocaleString();

      doc.text(userName.substring(0, 20), 14, y);
      doc.text(typeName.substring(0, 18), 60, y);
      doc.text(captured.substring(0, 25), 100, y);
      doc.text(time, 150, y);

      y += 7;
    });

    doc.save(`CyberAware-Report-${new Date().toISOString().slice(0, 10)}.pdf`);
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-indigo-100 flex items-center justify-center">
        <div className="text-xl font-medium text-indigo-600 animate-pulse">Loading dashboard...</div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-indigo-100">
      {/* Header */}
      <header className="bg-white/80 backdrop-blur-md shadow-sm border-b border-white/20 sticky top-0 z-10">
        <div className="max-w-7xl mx-auto px-6 py-4 flex justify-between items-center">
          <div className="flex items-center gap-4">
            <div className="p-2 bg-indigo-100 rounded-lg">
              <Shield className="h-8 w-8 text-indigo-600" />
            </div>
            <h1 className="text-2xl font-bold bg-gradient-to-r from-indigo-600 to-purple-600 bg-clip-text text-transparent">
              CyberAware Admin
            </h1>
          </div>
          <div className="flex items-center gap-6">
            <span className="text-sm text-gray-600 font-medium px-3 py-1 bg-gray-100 rounded-full">
              {userData?.name || user?.email}
            </span>
            <button
              onClick={() => signOut().then(() => router.push('/login'))}
              className="flex items-center gap-2 text-red-600 hover:text-red-700 font-medium hover:bg-red-50 px-3 py-2 rounded-lg transition-colors"
            >
              <LogOut className="h-5 w-5" /> Sign Out
            </button>
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-6 py-10">
        <div className="flex justify-between items-end mb-8">
          <div>
            <h2 className="text-3xl font-bold text-gray-900">Phishing Simulation Dashboard</h2>
            <p className="text-gray-600 mt-2">Monitor and analyze security awareness training performance</p>
          </div>
        </div>

        {/* Stats Cards */}
        <div className="grid md:grid-cols-3 gap-6 mb-10">
          <div className="bg-white/90 backdrop-blur-sm rounded-2xl shadow-xl ring-1 ring-black/5 p-6 transform hover:scale-105 transition-transform duration-200">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-gray-600 font-medium">Total Attempts</p>
                <p className="text-4xl font-bold text-gray-900 mt-2">{stats?.totalAttempts || 0}</p>
              </div>
              <div className="p-3 bg-red-100 rounded-xl">
                <AlertTriangle className="h-8 w-8 text-red-600" />
              </div>
            </div>
          </div>

          <div className="bg-white/90 backdrop-blur-sm rounded-2xl shadow-xl ring-1 ring-black/5 p-6 transform hover:scale-105 transition-transform duration-200">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-gray-600 font-medium">Users Tested</p>
                <p className="text-4xl font-bold text-gray-900 mt-2">{stats?.uniqueUsers || 0}</p>
              </div>
              <div className="p-3 bg-indigo-100 rounded-xl">
                <Users className="h-8 w-8 text-indigo-600" />
              </div>
            </div>
          </div>

          <div className="bg-white/90 backdrop-blur-sm rounded-2xl shadow-xl ring-1 ring-black/5 p-6 transform hover:scale-105 transition-transform duration-200">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-gray-600 font-medium">Avg Attempts / User</p>
                <p className="text-4xl font-bold text-gray-900 mt-2">
                  {stats?.uniqueUsers ? (stats.totalAttempts / stats.uniqueUsers).toFixed(1) : '0'}
                </p>
              </div>
              <div className="p-3 bg-purple-100 rounded-xl">
                <Shield className="h-8 w-8 text-purple-600" />
              </div>
            </div>
          </div>
        </div>

        {/* Attack Type Summary */}
        <div className="bg-white/90 backdrop-blur-sm rounded-2xl shadow-xl ring-1 ring-black/5 p-8 mb-10">
          <h3 className="text-xl font-bold text-gray-900 mb-6">Attempts by Type</h3>
          <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
            {types.map(t => (
              <div
                key={t.id}
                onClick={() => setSelectedFilter(t.id)}
                className={`${t.color} rounded-xl p-4 text-center cursor-pointer hover:shadow-md hover:scale-105 transition-all duration-200 border border-transparent hover:border-current`}
              >
                <div className="text-3xl mb-3">{t.icon}</div>
                <p className="font-medium text-sm opacity-90">{t.name}</p>
                <p className="text-2xl font-bold mt-2">{stats?.byType?.[t.id] || 0}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Recent Attempts Table */}
        <div className="bg-white/90 backdrop-blur-sm rounded-2xl shadow-xl ring-1 ring-black/5 overflow-hidden">
          <div className="bg-gradient-to-r from-indigo-600 to-purple-600 p-6 flex flex-col md:flex-row justify-between items-center gap-4">
            <h3 className="text-xl font-bold text-white flex items-center gap-3">
              <AlertTriangle className="h-6 w-6" />
              Recent Phishing Attempts
            </h3>
            <select
              value={selectedFilter}
              onChange={(e) => setSelectedFilter(e.target.value)}
              className="bg-white/10 text-white border border-white/20 font-medium px-4 py-2 rounded-lg focus:outline-none focus:ring-2 focus:ring-white/50 backdrop-blur-md"
            >
              <option value="all" className="text-gray-900">All Types</option>
              {types.map(t => (
                <option key={t.id} value={t.id} className="text-gray-900">{t.name}</option>
              ))}
            </select>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full">
              <thead className="bg-gray-50/50 border-b border-gray-100">
                <tr>
                  <th className="px-6 py-4 text-left text-sm font-semibold text-gray-600">User</th>
                  <th className="px-6 py-4 text-left text-sm font-semibold text-gray-600">Type</th>
                  <th className="px-6 py-4 text-left text-sm font-semibold text-gray-600">Data Captured</th>
                  <th className="px-6 py-4 text-left text-sm font-semibold text-gray-600">Time</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100">
                {filteredAttempts.length === 0 ? (
                  <tr>
                    <td colSpan={4} className="text-center py-12 text-gray-500">
                      No attempts recorded yet
                    </td>
                  </tr>
                ) : (
                  filteredAttempts.slice(0, 20).map((a) => (
                    <tr key={a.id} className="hover:bg-indigo-50/30 transition-colors">
                      <td className="px-6 py-4">
                        <div>
                          <p className="font-medium text-gray-900">{userMap[a.userId] || 'Unknown User'}</p>
                          <p className="text-xs text-gray-500 font-mono">{a.userId.slice(0, 8)}...</p>
                        </div>
                      </td>
                      <td className="px-6 py-4">
                        <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${types.find(t => t.id === a.phishingType)?.color || 'bg-gray-100 text-gray-800'
                          }`}>
                          {types.find(t => t.id === a.phishingType)?.name || a.phishingType}
                        </span>
                      </td>
                      <td className="px-6 py-4">
                        {Object.keys(a.capturedData || {}).length > 0 ? (
                          <div className="flex flex-wrap gap-1">
                            {Object.keys(a.capturedData).map(key => (
                              <span key={key} className="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-red-50 text-red-700 border border-red-100">
                                {key}
                              </span>
                            ))}
                          </div>
                        ) : (
                          <span className="text-green-600 text-sm flex items-center gap-1">
                            <Shield className="h-3 w-3" /> Safe
                          </span>
                        )}
                      </td>
                      <td className="px-6 py-4 text-sm text-gray-500">
                        {new Date(a.timestamp).toLocaleString()}
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="mt-10 flex flex-col sm:flex-row justify-center gap-6">
          <Link
            href="/admin/users"
            className="group relative inline-flex items-center justify-center px-8 py-3 text-base font-medium text-white bg-white border border-transparent rounded-xl shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 transition-all duration-200"
          >
            <span className="absolute inset-0 w-full h-full bg-gradient-to-r from-green-500 to-emerald-600 rounded-xl opacity-100 group-hover:opacity-90 transition-opacity" />
            <span className="relative flex items-center gap-2">
              <Users className="h-5 w-5" /> Manage Users
            </span>
          </Link>

          <button
            onClick={exportPDF}
            className="group relative inline-flex items-center justify-center px-8 py-3 text-base font-medium text-white bg-white border border-transparent rounded-xl shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 transition-all duration-200"
          >
            <span className="absolute inset-0 w-full h-full bg-gradient-to-r from-indigo-600 to-purple-600 rounded-xl opacity-100 group-hover:opacity-90 transition-opacity" />
            <span className="relative flex items-center gap-2">
              <Download className="h-5 w-5" /> Export Report (PDF)
            </span>
          </button>
        </div>
      </main>
    </div>
  );
}

// Wrap with ProtectedRoute
function AdminPage() {
  return (
    <ProtectedRoute allowedRoles={['admin']}>
      <AdminDashboard />
    </ProtectedRoute>
  );
}
